//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class arrendador
    {
        public arrendador()
        {
            this.espacio = new HashSet<espacio>();
        }
    
        public int idArrendador { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string dni { get; set; }
        public int edad { get; set; }
        public string nacionalidad { get; set; }
    
        public virtual ICollection<espacio> espacio { get; set; }
    }
}
