//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conductor
    {
        public Conductor()
        {
            this.Brevete = new HashSet<Brevete>();
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int IdConductor { get; set; }
        public int IdPersona { get; set; }
    
        public virtual ICollection<Brevete> Brevete { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
