//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espacio
    {
        public Espacio()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int IdEspacio { get; set; }
        public int IdArrendador { get; set; }
        public decimal TarifaHora { get; set; }
        public string Ubicacion { get; set; }
        public decimal Area { get; set; }
        public bool Estado { get; set; }
    
        public virtual Arrendador Arrendador { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
