//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDFEEntities : DbContext
    {
        public BDFEEntities()
            : base("name=BDFEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<arrendador> arrendador { get; set; }
        public DbSet<conductor> conductor { get; set; }
        public DbSet<espacio> espacio { get; set; }
        public DbSet<reserva> reserva { get; set; }
        public DbSet<vehiculo> vehiculo { get; set; }
    }
}
