//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDFEntities : DbContext
    {
        public BDFEntities()
            : base("name=BDFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Arrendador> Arrendador { get; set; }
        public DbSet<Brevete> Brevete { get; set; }
        public DbSet<Conductor> Conductor { get; set; }
        public DbSet<Espacio> Espacio { get; set; }
        public DbSet<Persona> Persona { get; set; }
        public DbSet<Reserva> Reserva { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Vehiculo> Vehiculo { get; set; }
    }
}
