//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        public int idReserva { get; set; }
        public int idVehiculo { get; set; }
        public int idEspacio { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime hora { get; set; }
        public int cantHoras { get; set; }
        public decimal montoTotal { get; set; }
    
        public virtual espacio espacio { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
