//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public Vehiculo()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int IdVehiculo { get; set; }
        public string Matricula { get; set; }
        public int IdConductor { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Color { get; set; }
    
        public virtual Conductor Conductor { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
