//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public vehiculo()
        {
            this.reserva = new HashSet<reserva>();
        }
    
        public int idVehiculo { get; set; }
        public int idConductor { get; set; }
        public string matricula { get; set; }
        public string marcaModelo { get; set; }
        public string tipo { get; set; }
        public string color { get; set; }
        public int cantAsientos { get; set; }
    
        public virtual conductor conductor { get; set; }
        public virtual ICollection<reserva> reserva { get; set; }
    }
}
